[package]
name = "metal_os"
version = "0.1.0"
authors = ["Vilas Chitrakaran <cvilas@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort" # disable stack unwinding on panic

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.8"
